apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  annotations:
    keel.sh/policy: "force"
    keel.sh/trigger: poll      
    keel.sh/approvals: "1"         
    keel.sh/pollSchedule: "@every 1m"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: bhc.jfrog.io/docker-development-local/webapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
      imagePullSecrets:
      - name: docker-creds
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: 34.74.23.31.nip.io
    http:
      paths:
      - backend:
          serviceName: webapp
          servicePort: 5000
        path: /
