apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  annotations:
    keel.sh/policy: "force"
    keel.sh/trigger: poll      
    keel.sh/approvals: "1"         
    keel.sh/pollSchedule: "@every 1m"
    keel.sh/releaseNotes: "https://github.com/damianesteban/gke-test-deploy/releases"

spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: betterptdev/webapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
      imagePullSecrets:
      - name: dockerhub
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP


